name: Azure Developer CLI Deploy

on:
  workflow_dispatch:
  # Disabled auto-trigger to avoid conflicts with main deploy workflow
  # push:
  #   branches:
  #     - main
  #     - master

permissions:
  id-token: write
  contents: read

env:
  AZURE_ENV_NAME: 'webapplication1'
  AZURE_LOCATION: 'East US'

jobs:
  azd-deploy:
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Install Azure Developer CLI
      uses: Azure/setup-azd@v1.0.0
      
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure Developer CLI Deploy
      run: |
        azd config set auth.useAzCliAuth true
        azd env new ${{ env.AZURE_ENV_NAME }} --location "${{ env.AZURE_LOCATION }}" --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}" --confirm
        azd deploy --no-prompt
      shell: bash
      env:
        AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}
        AZURE_LOCATION: ${{ env.AZURE_LOCATION }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
