name: Azure Developer CLI Deploy

on:
  workflow_dispatch:
  # Disabled auto-trigger to avoid conflicts with main deploy workflow
  # push:
  #   branches:
  #     - main
  #     - master

permissions:
  id-token: write
  contents: read

env:
  AZURE_ENV_NAME: 'webapplication1'
  AZURE_LOCATION: 'East US'

jobs:
  azd-deploy:
    runs-on: ubuntu-latest
    # Removed environment requirement to avoid configuration issues
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Install Azure Developer CLI
      uses: Azure/setup-azd@v1.0.0
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Verify Azure CLI Login
      run: |
        echo "Verifying Azure CLI login..."
        az account show
        az account list --output table
      shell: bash
        
    - name: Azure Developer CLI Deploy
      run: |
        # Configure AZD to use Azure CLI authentication
        azd config set auth.useAzCliAuth true
        
        # Set environment variables
        azd env set AZURE_SUBSCRIPTION_ID "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        azd env set AZURE_LOCATION "${{ env.AZURE_LOCATION }}"
        
        # Create or select environment
        if azd env list | grep -q "${{ env.AZURE_ENV_NAME }}"; then
          echo "Environment ${{ env.AZURE_ENV_NAME }} exists, selecting it"
          azd env select ${{ env.AZURE_ENV_NAME }}
        else
          echo "Creating new environment ${{ env.AZURE_ENV_NAME }}"
          azd env new ${{ env.AZURE_ENV_NAME }} --location "${{ env.AZURE_LOCATION }}" --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}" --confirm
        fi
        
        # Deploy the application
        azd deploy --no-prompt
      shell: bash
      env:
        AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}
        AZURE_LOCATION: ${{ env.AZURE_LOCATION }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
