name: Deploy to Azure

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'
  AZURE_WEBAPP_NAME: 'app-webapp-auvx5tx4cnram'
  RESOURCE_GROUP_NAME: 'rg-webapplication1'
  AZURE_ENV_NAME: 'webapplication1'
  AZURE_LOCATION: 'East US'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore ./WebApplication1
      
    - name: Build application
      run: dotnet build ./WebApplication1 --configuration Release --no-restore
      
    - name: Test application
      run: dotnet test ./WebApplication1 --configuration Release --no-build --verbosity normal
      continue-on-error: true
      
    - name: Publish application
      run: dotnet publish ./WebApplication1 --configuration Release --no-build --output ./publish
      
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Create Resource Group if not exists
      run: |
        if ! az group show --name ${{ env.RESOURCE_GROUP_NAME }} &> /dev/null; then
          echo "Creating resource group ${{ env.RESOURCE_GROUP_NAME }}"
          az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location "${{ env.AZURE_LOCATION }}"
        else
          echo "Resource group ${{ env.RESOURCE_GROUP_NAME }} already exists"
        fi
      shell: bash
        
    - name: Deploy Azure infrastructure
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
        template: ./infra/main.bicep
        parameters: ./infra/main.parameters.json environmentName=${{ env.AZURE_ENV_NAME }} location="${{ env.AZURE_LOCATION }}"
        deploymentMode: Incremental
        deploymentName: 'github-deployment-${{ github.run_number }}'
      continue-on-error: true
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./publish
        
    - name: Health Check
      run: |
        echo "Waiting for app to be ready..."
        sleep 30
        curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net || echo "Health check failed but continuing"
      shell: bash
      continue-on-error: true
