name: Deploy to Azure

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'
  AZURE_WEBAPP_NAME: 'app-webapp-auvx5tx4cnram'
  RESOURCE_GROUP_NAME: 'rg-webapplication1'
  AZURE_ENV_NAME: 'webapplication1'
  AZURE_LOCATION: 'East US'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore ./WebApplication1
      
    - name: Build application
      run: dotnet build ./WebApplication1 --configuration Release --no-restore
      
    - name: Test application
      run: dotnet test ./WebApplication1 --configuration Release --no-build --verbosity normal
      continue-on-error: true
      
    - name: Publish application
      run: dotnet publish ./WebApplication1 --configuration Release --no-build --output ./publish
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Verify Azure CLI Login
      run: |
        echo "Verifying Azure CLI login..."
        az account show
      shell: bash
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./publish
        
    - name: Health Check
      run: |
        echo "Waiting for app to be ready..."
        sleep 30
        curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net || echo "Health check failed but continuing"
      shell: bash
      continue-on-error: true
